### ISSUE TITLE
Make sure that TS types work

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/getdesktopenv#1]
I think that I've heard from @jimmywarting that you can use JSDoc types and get type inference on the consuming-side of things? I need to:
1. test this as a client
2. google some more?
3. ask someone else to see if they know from experience

**Comment by jimmywarting** [comment]
seems to work fine to me...
tested installing it using npm

got the correct types

![Skärmavbild 2023-06-10 kl  13 06 33](https://github.com/jcbhmr/getdesktopenv/assets/1148376/a38fd60d-00b1-46fc-bcc9-e8451990edae)

![Skärmavbild 2023-06-10 kl  13 06 38](https://github.com/jcbhmr/getdesktopenv/assets/1148376/34bf6a25-3b23-4f0e-96db-cc34c4db8427)

---

Heck even using deno's own official vscode extension are able to download & cache the typing from http import

![Skärmavbild 2023-06-10 kl  13 18 31](https://github.com/jcbhmr/getdesktopenv/assets/1148376/c1fb0c84-95c4-4258-8c3b-84733cddffff)

**Comment by jcbhmr** [comment]
You're right! It does work.
![image](https://github.com/jcbhmr/getdesktopenv/assets/61068799/e80e3f7d-1e51-403b-b768-25851ef2fd8c)

Any idea why it still shows a little "did not find types for this module" warning? 🤔 Is this a bbug in TS? Intended behavior? Just a quirk of using JSDoc instead of .d.ts?
![image](https://github.com/jcbhmr/getdesktopenv/assets/61068799/3f2011b5-9a25-4ad9-8703-6efcc52d6949)

**Comment by jimmywarting** [comment]
I suppose it will try to look for `@types/<pkg_name>` and try to download some matching package if the package itself dose not contain any type definitions (`d.ts`). Then can also be generated out of JSDocs but i honestly don't see the point in having to do that

**Comment by jcbhmr** [comment]
I'll assume that this is just a quirk of TypeScript right now and live with it 🤷‍♂️
